env:
  global:
    - CC_TEST_REPORTER_ID=a400c9100efae66a7bd9bd11aca0118bb516dca7af9471d08c735361a11082f5
language: java
dist: bionic
services:
  - xvfb
jdk:
- openjdk9
before_script:
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build
script:
  - ./gradlew clean build jacocoTestReport
after_script:
  - JACOCO_SOURCE_PATH=src/main/java ./cc-test-reporter format-coverage ./build/reports/jacoco/test/jacocoTestReport.xml --input-type jacoco
  - ./cc-test-reporter upload-coverage -r $CC_TEST_REPORTER_ID
  - bash ./telegram_notification.sh

