env:
  global:
  - CC_TEST_REPORTER_ID=cd9dce60ab1686b279c6b871d4f5171e3dc3d17426617eb12db6cfee74da898c
language: java
dist: bionic
jdk:
- openjdk8
- openjdk9
before_script:
- curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64
  > ./cc-test-reporter
- chmod +x ./cc-test-reporter
- ./cc-test-reporter before-build
script:
- ./gradlew clean build jacocoTestReport
after_script:
- JACOCO_SOURCE_PATH=src ./cc-test-reporter format-coverage ./build/reports/jacoco/test/jacocoTestReport.xml
  --input-type jacoco
- ./cc-test-reporter upload-coverage -r $CC_TEST_REPORTER_ID
